[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_stages = "3fmuFJf2auxKMBJsx5YrUyRosi9yBGUz4vyPhLZTCY6P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rehanmohammed/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
